# AirGradient Open Air Outdoor Monitor with CO2 and TVOC
# Model: O-1PST
# https://www.airgradient.com/open-airgradient/instructions/overview/

substitutions:
  name: "ag-open-air-o-1pst"
  friendly_name: "AG Open Air O-1PST"
  name_add_mac_suffix: "false"  # Must have quotes around value

# Enable Home Assistant API
api:  # Add encryption key as desired

ota:  # Add password as desired
  platform: esphome
  # password:

wifi:

dashboard_import:
  package_import_url: github://spiceywasabi/airgradient_esphome/airgradient-open-air-o-1pst.yaml
  import_full_config: false

packages:
  board: github://spiceywasabi/airgradient_esphome/packages/airgradient_esp32-c3_board.yaml
  captive_portal: github://spiceywasabi/airgradient_esphome/packages/captive_portal.yaml
  pm_2.5: github://spiceywasabi/airgradient_esphome/packages/sensor_pms5003t.yaml
  # pm_2.5: github://spiceywasabi/airgradient_esphome/packages/sensor_pms5003t_extended_life.yaml
  co2: github://spiceywasabi/airgradient_esphome/packages/sensor_s8.yaml
  tvoc: github://spiceywasabi/airgradient_esphome/packages/sensor_sgp41.yaml
  airgradient_api: github://spiceywasabi/airgradient_esphome/packages/airgradient_api_esp32-c3.yaml
  hardware_watchdog: github://spiceywasabi/airgradient_esphome/packages/watchdog.yaml
  wifi: github://spiceywasabi/airgradient_esphome/packages/sensor_wifi.yaml
  uptime: github://spiceywasabi/airgradient_esphome/packages/sensor_uptime.yaml
