---
# AirGradient DIY Basic
# https://www.airgradient.com/open-airgradient/instructions/overview/

substitutions:
  name: "ag-basic"
  friendly_name: "AG Basic"
  name_add_mac_suffix: "false"  # Must have quotes around value

# Enable Home Assistant API
api:  # Add encryption key as desired

ota:  # Add password as desired
  platform: esphome
  # password:

wifi:

dashboard_import:
  package_import_url: github://spiceywasabi/airgradient_esphome/airgradient-basic.yaml
  import_full_config: false

packages:
  board: github://spiceywasabi/airgradient_esphome/packages/airgradient_d1_mini_board.yaml
  captive_portal: github://spiceywasabi/airgradient_esphome/packages/captive_portal.yaml
  pm_2.5: github://spiceywasabi/airgradient_esphome/packages/sensor_pms5003.yaml
  co2: github://spiceywasabi/airgradient_esphome/packages/sensor_s8.yaml
  # temp_humidity: github://spiceywasabi/airgradient_esphome/packages/sensor_sht40.yaml
  temp_humidity: github://spiceywasabi/airgradient_esphome/packages/sensor_sht30.yaml
  display: github://spiceywasabi/airgradient_esphome/packages/display_ssd1306.yaml
  airgradient_api: github://spiceywasabi/airgradient_esphome/packages/airgradient_api_d1_mini_no_sgp41.yaml
  wifi: github://spiceywasabi/airgradient_esphome/packages/sensor_wifi.yaml
  uptime: github://spiceywasabi/airgradient_esphome/packages/sensor_uptime.yaml
