bme68x_bsec2_i2c:
  model: bme680
  operating_age: 28d
  supply_voltage: 3.3V

sensor:
  - platform: bme68x_bsec2
    temperature:
      name: "BME68x Temperature"
      id: bme_temp
    pressure:
      name: "BME68x Pressure"
      id: bme_pressure
    humidity:
      name: "BME68x Humidity"
      id: bme_humidity
    iaq:
      name: "BME68x IAQ"
      id: iaq
    co2_equivalent:
      name: "BME68x CO2 Equivalent"
      id: bme_eco2
    breath_voc_equivalent:
      name: "BME68x Breath VOC Equivalent"
      id: bme_voc
  - platform: bme680_bsec2
    temperature:
      name: "BME680 BSEC Temperature"
      id: bme_temp
    pressure:
      name: "BME680 BSEC Pressure"
      id: bme_pressure
    humidity:
      name: "BME680 BSEC Humidity"
      id: bme_humidity
    iaq:
      name: "BME680 BSEC IAQ"
      id: bme_iaq
    co2_equivalent:
      name: "BME680 BSEC CO2 Equivalent"
      id: bme_eco2
    breath_voc_equivalent:
      name: "BME680 BSEC Breath VOC Equivalent"
      id: bme_voc

text_sensor:
  - platform: bme680_bsec2
    iaq_accuracy:
      name: "BME680 IAQ Accuracy"
      id: iaq_accuracy

  - platform: template
    name: "BME680 IAQ Classification"
    icon: "mdi:checkbox-marked-circle-outline"
    id: iaq_classification
    lambda: |-
      if ( int(id(bme_iaq).state) <= 50) {
        return {"Excellent"};
      }
      else if (int(id(bme_iaq).state) >= 51 && int(id(bme_iaq).state) <= 100) {
        return {"Good"};
      }
      else if (int(id(bme_iaq).state) >= 101 && int(id(bme_iaq).state) <= 150) {
        return {"Lightly polluted"};
      }
      else if (int(id(bme_iaq).state) >= 151 && int(id(bme_iaq).state) <= 200) {
        return {"Moderately polluted"};
      }
      else if (int(id(bme_iaq).state) >= 201 && int(id(bme_iaq).state) <= 250) {
        return {"Heavily polluted"};
      }
      else if (int(id(bme_iaq).state) >= 251 && int(id(bme_iaq).state) <= 350) {
        return {"Severely polluted"};
      }
      else if (int(id(bme_iaq).state) >= 351) {
        return {"Extremely polluted"};
      }
      else {
        return {"error"};
      }
